/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData run = const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings2 = const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
